### ISSUE TITLE
Exit code 4 when trying to load with Descriptions

### ISSUE THREAD

**Issue by JoePotentier** [CircleCI-Public/aws-parameter-store-orb#20]
Configuration:

```
 steps:
      - aws-parameter-store/load:
          # Filter syntax ref https://docs.aws.amazon.com/cli/latest/reference/ssm/describe-parameters.html#options
          filter: Key=Name,Values=CONTAINER_REGISTRY_URL
```

parse error: Unfinished string at EOF at line 2, column 0

Exited with code exit status 4

Running the commands on my local system the error seems to arise from this line:
```
PARNAME=$(jq -r '.Name' <<< "${row}")
```

and the bug has something to do with the description having newline characters in it.

I'll make a PR to address this.
